#version 1.9

myjava:
 build: ./Java
 tty: true

myjira:
 build: ./Jira
 tty: true
 ports: 
  - 8080:8080

myjenkins:
 build: ./Jenkins
 links:
  - myjava
 ports:
  - 8086:8080
 tty: true

mytomcat:
 build: ./TomCat
 links:
  - myjava
 ports:
  - 8090:8080
 tty: true

mynexus:
 build: ./Nexus
 links:
  - myjava
 ports: 
  - 8012:8081
 tty: true
 
